let NUsuario =Number(prompt ("digite um numero par"))
console.log=Number(NUsuario)
console.log("o resto da divisão por 2 é:",NUsuario %2)
//  O numero sempre vai ser PAR quando o resto da divisão é zero (0)
// se o usario inserir um numero IMPAR o resto da divisão e um (1)